### ISSUE TITLE
I'd like to reference your repo in mine

### ISSUE THREAD

**Issue by scraggo** [artemave/node-test-runners-performance-comparison#1]
Would you mind if I added your repo as a reference link in my article? https://github.com/scraggo/comparing-javascript-test-runners

If you're so inclined, you have permission to add mine as well.

Thank you for the great work!

**Comment by artemave** [comment]
> Would you mind if I added your repo as a reference link in my article? https://github.com/scraggo/comparing-javascript-test-runners

Of course I wouldn't - be my guest.

> Thank you for the great work!

You're welcome!
